version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_gestao_vagas
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestao_vagas
    ports:
      - "5433:5432"  # Mudei para 5433 para evitar conflito
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d gestao_vagas"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: